// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classes.sql

package sqlcdb

import (
	"context"
)

const createClass = `-- name: CreateClass :one

INSERT INTO classes (id, instructor_id, title, description)
VALUES ($1, $2, $3, $4)
RETURNING id, instructor_id, title, description, status, created_at
`

type CreateClassParams struct {
	ID           string
	InstructorID string
	Title        string
	Description  string
}

// Classes: instructor course definitions.
func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, createClass,
		arg.ID,
		arg.InstructorID,
		arg.Title,
		arg.Description,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.InstructorID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getClass = `-- name: GetClass :one
SELECT id, instructor_id, title, description, status, created_at
FROM classes WHERE id = $1
`

func (q *Queries) GetClass(ctx context.Context, id string) (Class, error) {
	row := q.db.QueryRow(ctx, getClass, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.InstructorID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listClassesByInstructor = `-- name: ListClassesByInstructor :many
SELECT id, instructor_id, title, description, status, created_at
FROM classes WHERE instructor_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListClassesByInstructor(ctx context.Context, instructorID string) ([]Class, error) {
	rows, err := q.db.Query(ctx, listClassesByInstructor, instructorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.InstructorID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedClasses = `-- name: ListPublishedClasses :many
SELECT id, instructor_id, title, description, status, created_at
FROM classes WHERE status = 'published'
ORDER BY created_at DESC
LIMIT 100
`

// Public catalog: published classes, newest first (bounded).
func (q *Queries) ListPublishedClasses(ctx context.Context) ([]Class, error) {
	rows, err := q.db.Query(ctx, listPublishedClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.InstructorID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClassStatus = `-- name: UpdateClassStatus :exec
UPDATE classes SET status = $2 WHERE id = $1
`

type UpdateClassStatusParams struct {
	ID     string
	Status string
}

func (q *Queries) UpdateClassStatus(ctx context.Context, arg UpdateClassStatusParams) error {
	_, err := q.db.Exec(ctx, updateClassStatus, arg.ID, arg.Status)
	return err
}
