// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_login.sql

package sqlcdb

import (
	"context"
	"time"
)

const consumeLoginChallenge = `-- name: ConsumeLoginChallenge :exec
UPDATE login_challenges SET consumed_at = now() WHERE id = $1
`

func (q *Queries) ConsumeLoginChallenge(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, consumeLoginChallenge, id)
	return err
}

const createLoginChallenge = `-- name: CreateLoginChallenge :exec
INSERT INTO login_challenges (id, email, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateLoginChallengeParams struct {
	ID        string
	Email     string
	CodeHash  []byte
	ExpiresAt time.Time
}

func (q *Queries) CreateLoginChallenge(ctx context.Context, arg CreateLoginChallengeParams) error {
	_, err := q.db.Exec(ctx, createLoginChallenge,
		arg.ID,
		arg.Email,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	return err
}

const getActiveLoginChallenge = `-- name: GetActiveLoginChallenge :one
SELECT id, email, code_hash, attempts, expires_at, consumed_at, created_at
FROM login_challenges
WHERE email = $1 AND consumed_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

// The newest unconsumed, unexpired challenge for an email.
func (q *Queries) GetActiveLoginChallenge(ctx context.Context, email string) (LoginChallenge, error) {
	row := q.db.QueryRow(ctx, getActiveLoginChallenge, email)
	var i LoginChallenge
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailIdentity = `-- name: GetEmailIdentity :one

SELECT email, user_id, created_at, last_login
FROM email_identities
WHERE email = $1
`

// First-party email-OTP login. Login factor only; never adult eKYC.
func (q *Queries) GetEmailIdentity(ctx context.Context, email string) (EmailIdentity, error) {
	row := q.db.QueryRow(ctx, getEmailIdentity, email)
	var i EmailIdentity
	err := row.Scan(
		&i.Email,
		&i.UserID,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const incrementLoginChallengeAttempts = `-- name: IncrementLoginChallengeAttempts :exec
UPDATE login_challenges SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementLoginChallengeAttempts(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementLoginChallengeAttempts, id)
	return err
}

const linkEmailIdentity = `-- name: LinkEmailIdentity :exec
INSERT INTO email_identities (email, user_id)
VALUES ($1, $2)
`

type LinkEmailIdentityParams struct {
	Email  string
	UserID string
}

func (q *Queries) LinkEmailIdentity(ctx context.Context, arg LinkEmailIdentityParams) error {
	_, err := q.db.Exec(ctx, linkEmailIdentity, arg.Email, arg.UserID)
	return err
}

const touchEmailLogin = `-- name: TouchEmailLogin :exec
UPDATE email_identities SET last_login = now()
WHERE email = $1
`

func (q *Queries) TouchEmailLogin(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, touchEmailLogin, email)
	return err
}
