// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: federated.sql

package sqlcdb

import (
	"context"
)

const getFederatedIdentity = `-- name: GetFederatedIdentity :one

SELECT provider, subject, user_id, created_at, last_login
FROM federated_identities
WHERE provider = $1 AND subject = $2
`

type GetFederatedIdentityParams struct {
	Provider string
	Subject  string
}

// Federated (OIDC) login identities. Login factor only; never adult eKYC.
func (q *Queries) GetFederatedIdentity(ctx context.Context, arg GetFederatedIdentityParams) (FederatedIdentity, error) {
	row := q.db.QueryRow(ctx, getFederatedIdentity, arg.Provider, arg.Subject)
	var i FederatedIdentity
	err := row.Scan(
		&i.Provider,
		&i.Subject,
		&i.UserID,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const linkFederatedIdentity = `-- name: LinkFederatedIdentity :exec
INSERT INTO federated_identities (provider, subject, user_id)
VALUES ($1, $2, $3)
`

type LinkFederatedIdentityParams struct {
	Provider string
	Subject  string
	UserID   string
}

func (q *Queries) LinkFederatedIdentity(ctx context.Context, arg LinkFederatedIdentityParams) error {
	_, err := q.db.Exec(ctx, linkFederatedIdentity, arg.Provider, arg.Subject, arg.UserID)
	return err
}

const touchFederatedLogin = `-- name: TouchFederatedLogin :exec
UPDATE federated_identities SET last_login = now()
WHERE provider = $1 AND subject = $2
`

type TouchFederatedLoginParams struct {
	Provider string
	Subject  string
}

func (q *Queries) TouchFederatedLogin(ctx context.Context, arg TouchFederatedLoginParams) error {
	_, err := q.db.Exec(ctx, touchFederatedLogin, arg.Provider, arg.Subject)
	return err
}
