// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package sqlcdb

import (
	"context"
	"time"
)

const createIdentityRecord = `-- name: CreateIdentityRecord :exec

INSERT INTO identity_vault (user_id) VALUES ($1)
`

// identity_vault: the only place identity PII lives (encrypted at rest). These
// queries write verification *state* and opaque references; raw PII columns
// (full_name_enc, dob_enc, ...) are written by the eKYC ingestion path, not
// here. Retention (retain_until) follows Decree 147 (>= 24 months).
// Establishes the vault row in its default unverified, non-adult state.
func (q *Queries) CreateIdentityRecord(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, createIdentityRecord, userID)
	return err
}

const getIdentity = `-- name: GetIdentity :one
SELECT user_id, verification_status, is_adult, provider_ref, full_name_enc, dob_enc, phone_hash, email_enc, verified_at, retain_until
FROM identity_vault WHERE user_id = $1
`

func (q *Queries) GetIdentity(ctx context.Context, userID string) (IdentityVault, error) {
	row := q.db.QueryRow(ctx, getIdentity, userID)
	var i IdentityVault
	err := row.Scan(
		&i.UserID,
		&i.VerificationStatus,
		&i.IsAdult,
		&i.ProviderRef,
		&i.FullNameEnc,
		&i.DobEnc,
		&i.PhoneHash,
		&i.EmailEnc,
		&i.VerifiedAt,
		&i.RetainUntil,
	)
	return i, err
}

const revokeIdentityVerification = `-- name: RevokeIdentityVerification :exec
UPDATE identity_vault
SET verification_status = 'none',
    is_adult = false,
    verified_at = NULL
WHERE user_id = $1
`

// Reverses verification (e.g. eKYC reversal, fraud finding). Defence in depth:
// a trigger demotes any active user whose identity is revoked this way.
func (q *Queries) RevokeIdentityVerification(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeIdentityVerification, userID)
	return err
}

const verifyAdultIdentity = `-- name: VerifyAdultIdentity :exec
UPDATE identity_vault
SET verification_status = 'verified',
    is_adult = true,
    provider_ref = $2,
    verified_at = now(),
    retain_until = $3
WHERE user_id = $1
`

type VerifyAdultIdentityParams struct {
	UserID      string
	ProviderRef *string
	RetainUntil *time.Time
}

// Records a successful eKYC: verified adult. This is the state the activation
// trigger requires before a user may go active.
func (q *Queries) VerifyAdultIdentity(ctx context.Context, arg VerifyAdultIdentityParams) error {
	_, err := q.db.Exec(ctx, verifyAdultIdentity, arg.UserID, arg.ProviderRef, arg.RetainUntil)
	return err
}
