// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"time"
)

type IdentityVault struct {
	UserID             string
	VerificationStatus string
	IsAdult            bool
	ProviderRef        *string
	FullNameEnc        []byte
	DobEnc             []byte
	PhoneHash          []byte
	EmailEnc           []byte
	VerifiedAt         *time.Time
	RetainUntil        *time.Time
}

type RefreshToken struct {
	ID           string
	UserID       string
	FamilyID     string
	TokenHash    []byte
	ExpiresAt    time.Time
	RevokedAt    *time.Time
	ReplacedByID *string
	CreatedAt    time.Time
}

type RevokedToken struct {
	Jti       string
	ExpiresAt time.Time
	RevokedAt time.Time
}

type Session struct {
	ID             string
	Kind           string
	ClassID        *string
	LivekitRoom    string
	Status         string
	ScheduledStart *time.Time
	StartedAt      *time.Time
	EndedAt        *time.Time
	CreatedAt      time.Time
}

type SessionParticipant struct {
	SessionID string
	UserID    string
	Role      string
	JoinedAt  time.Time
	LeftAt    *time.Time
}

type TosAcceptance struct {
	UserID        string
	TosVersion    string
	AdultAttested bool
	AcceptedAt    time.Time
}

type User struct {
	ID                  string
	Handle              string
	DisplayName         string
	Bio                 *string
	Locale              string
	Status              string
	CanInstruct         bool
	IsPlatformModerator bool
	TokenVersion        int32
	CreatedAt           time.Time
	DeletedAt           *time.Time
}
