// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phone_login.sql

package sqlcdb

import (
	"context"
	"time"
)

const consumePhoneChallenge = `-- name: ConsumePhoneChallenge :exec
UPDATE phone_challenges SET consumed_at = now() WHERE id = $1
`

func (q *Queries) ConsumePhoneChallenge(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, consumePhoneChallenge, id)
	return err
}

const createPhoneChallenge = `-- name: CreatePhoneChallenge :exec
INSERT INTO phone_challenges (id, phone, code_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreatePhoneChallengeParams struct {
	ID        string
	Phone     string
	CodeHash  []byte
	ExpiresAt time.Time
}

func (q *Queries) CreatePhoneChallenge(ctx context.Context, arg CreatePhoneChallengeParams) error {
	_, err := q.db.Exec(ctx, createPhoneChallenge,
		arg.ID,
		arg.Phone,
		arg.CodeHash,
		arg.ExpiresAt,
	)
	return err
}

const getActivePhoneChallenge = `-- name: GetActivePhoneChallenge :one
SELECT id, phone, code_hash, attempts, expires_at, consumed_at, created_at
FROM phone_challenges
WHERE phone = $1 AND consumed_at IS NULL AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetActivePhoneChallenge(ctx context.Context, phone string) (PhoneChallenge, error) {
	row := q.db.QueryRow(ctx, getActivePhoneChallenge, phone)
	var i PhoneChallenge
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.CodeHash,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPhoneIdentity = `-- name: GetPhoneIdentity :one

SELECT phone, user_id, created_at, last_login
FROM phone_identities
WHERE phone = $1
`

// Phone one-time-code factor: login + the phone_verified assurance tier.
func (q *Queries) GetPhoneIdentity(ctx context.Context, phone string) (PhoneIdentity, error) {
	row := q.db.QueryRow(ctx, getPhoneIdentity, phone)
	var i PhoneIdentity
	err := row.Scan(
		&i.Phone,
		&i.UserID,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getPhoneIdentityByUser = `-- name: GetPhoneIdentityByUser :one
SELECT phone, user_id, created_at, last_login
FROM phone_identities
WHERE user_id = $1
`

func (q *Queries) GetPhoneIdentityByUser(ctx context.Context, userID string) (PhoneIdentity, error) {
	row := q.db.QueryRow(ctx, getPhoneIdentityByUser, userID)
	var i PhoneIdentity
	err := row.Scan(
		&i.Phone,
		&i.UserID,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const hasVerifiedPhone = `-- name: HasVerifiedPhone :one
SELECT EXISTS (SELECT 1 FROM phone_identities WHERE user_id = $1)
`

func (q *Queries) HasVerifiedPhone(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasVerifiedPhone, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const incrementPhoneChallengeAttempts = `-- name: IncrementPhoneChallengeAttempts :exec
UPDATE phone_challenges SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementPhoneChallengeAttempts(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, incrementPhoneChallengeAttempts, id)
	return err
}

const linkPhoneIdentity = `-- name: LinkPhoneIdentity :exec
INSERT INTO phone_identities (phone, user_id)
VALUES ($1, $2)
`

type LinkPhoneIdentityParams struct {
	Phone  string
	UserID string
}

func (q *Queries) LinkPhoneIdentity(ctx context.Context, arg LinkPhoneIdentityParams) error {
	_, err := q.db.Exec(ctx, linkPhoneIdentity, arg.Phone, arg.UserID)
	return err
}

const touchPhoneLogin = `-- name: TouchPhoneLogin :exec
UPDATE phone_identities SET last_login = now()
WHERE phone = $1
`

func (q *Queries) TouchPhoneLogin(ctx context.Context, phone string) error {
	_, err := q.db.Exec(ctx, touchPhoneLogin, phone)
	return err
}
