// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
)

type Querier interface {
	// Subject to trg_enforce_adult_activation: fails unless a verified adult
	// identity exists for the user.
	ActivateUser(ctx context.Context, id string) error
	// Subject to trg_enforce_direct_session_cap for direct sessions.
	AddParticipant(ctx context.Context, arg AddParticipantParams) error
	// Revoke-all for a user: every outstanding access token (tver < new) is now
	// superseded. Returns the new version.
	BumpTokenVersion(ctx context.Context, id string) (int32, error)
	// identity_vault: the only place identity PII lives (encrypted at rest). These
	// queries write verification *state* and opaque references; raw PII columns
	// (full_name_enc, dob_enc, ...) are written by the eKYC ingestion path, not
	// here. Retention (retain_until) follows Decree 147 (>= 24 months).
	// Establishes the vault row in its default unverified, non-adult state.
	// Idempotent so bootstrap/relink paths can call it unconditionally.
	CreateIdentityRecord(ctx context.Context, userID string) error
	// Sessions and their participants. The kind/class_id coherence CHECK and the
	// direct-session participant cap are enforced DB-side; these queries surface
	// those guarantees rather than re-implementing them.
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Users: opaque-id accounts, no PII (PII lives in identity_vault). Activation
	// is gated DB-side by the verified-adult trigger; these queries never bypass it.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CurrentTokenVersion(ctx context.Context, id string) (int32, error)
	EndSession(ctx context.Context, id string) error
	// Resolves the rotation family a presented token belongs to (any state), so a
	// logout can revoke the whole chain.
	GetFamilyByHash(ctx context.Context, tokenHash []byte) (string, error)
	GetIdentity(ctx context.Context, userID string) (IdentityVault, error)
	// Locks the row for the duration of the rotation transaction so a token
	// presented concurrently cannot rotate twice (serialises reuse detection).
	GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetUser(ctx context.Context, id string) (User, error)
	// Login lookup. Case-insensitive (matches the lower(handle) unique index) and
	// excludes soft-deleted accounts.
	GetUserByHandle(ctx context.Context, lower string) (User, error)
	// Access-token revocation state (A-5): the parts of validation the stateless
	// signature check cannot answer. Backs token.RevocationStore.
	IsAccessTokenRevoked(ctx context.Context, jti string) (bool, error)
	// Refresh-token rotation chain (A-5). Tokens are opaque and stored only as a
	// hash; rotation is single-use with reuse detection at the family level.
	IssueRefreshToken(ctx context.Context, arg IssueRefreshTokenParams) error
	ListActiveParticipants(ctx context.Context, sessionID string) ([]SessionParticipant, error)
	MarkRefreshTokenReplaced(ctx context.Context, arg MarkRefreshTokenReplacedParams) error
	// Grants the platform-moderator capability (backs caps:platform_moderator).
	// Operator-only path (adminctl); never reachable from user-facing handlers.
	PromoteToModerator(ctx context.Context, id string) error
	RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error
	// Single-token revocation: denylist a jti until its natural expiry. Idempotent.
	RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) error
	// Reverses verification (e.g. eKYC reversal, fraud finding). Defence in depth:
	// a trigger demotes any active user whose identity is revoked this way.
	RevokeIdentityVerification(ctx context.Context, userID string) error
	// Theft response: revoke every live token in the rotation chain at once.
	RevokeRefreshFamily(ctx context.Context, familyID string) error
	SoftDeleteUser(ctx context.Context, id string) error
	StartSession(ctx context.Context, id string) error
	SuspendUser(ctx context.Context, id string) error
	UserExists(ctx context.Context, id string) (bool, error)
	// Records a successful eKYC: verified adult. This is the state the activation
	// trigger requires before a user may go active.
	VerifyAdultIdentity(ctx context.Context, arg VerifyAdultIdentityParams) error
}

var _ Querier = (*Queries)(nil)
