// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
)

type Querier interface {
	// Revoke-all for a user: every outstanding access token (tver < new) is now
	// superseded. Returns the new version.
	BumpTokenVersion(ctx context.Context, id string) (int32, error)
	CurrentTokenVersion(ctx context.Context, id string) (int32, error)
	// Locks the row for the duration of the rotation transaction so a token
	// presented concurrently cannot rotate twice (serialises reuse detection).
	GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	// Access-token revocation state (A-5): the parts of validation the stateless
	// signature check cannot answer. Backs token.RevocationStore.
	IsAccessTokenRevoked(ctx context.Context, jti string) (bool, error)
	// Refresh-token rotation chain (A-5). Tokens are opaque and stored only as a
	// hash; rotation is single-use with reuse detection at the family level.
	IssueRefreshToken(ctx context.Context, arg IssueRefreshTokenParams) error
	MarkRefreshTokenReplaced(ctx context.Context, arg MarkRefreshTokenReplacedParams) error
	// Single-token revocation: denylist a jti until its natural expiry. Idempotent.
	RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) error
	// Theft response: revoke every live token in the rotation chain at once.
	RevokeRefreshFamily(ctx context.Context, familyID string) error
}

var _ Querier = (*Queries)(nil)
