// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
)

type Querier interface {
	// Terms-of-Service acceptances, including the explicit 18+ self-attestation that
	// backs the 'declared' identity-assurance tier.
	// Idempotent per (user, version): re-accepting updates the attestation/time.
	AcceptToS(ctx context.Context, arg AcceptToSParams) error
	// Subject to trg_enforce_adult_activation: fails unless a verified adult
	// identity exists for the user.
	ActivateUser(ctx context.Context, id string) error
	// Subject to trg_enforce_direct_session_cap for direct sessions.
	AddParticipant(ctx context.Context, arg AddParticipantParams) error
	// Revoke-all for a user: every outstanding access token (tver < new) is now
	// superseded. Returns the new version.
	BumpTokenVersion(ctx context.Context, id string) (int32, error)
	ConsumeLoginChallenge(ctx context.Context, id string) error
	ConsumePhoneChallenge(ctx context.Context, id string) error
	// Classes: instructor course definitions.
	CreateClass(ctx context.Context, arg CreateClassParams) (Class, error)
	// identity_vault: the only place identity PII lives (encrypted at rest). These
	// queries write verification *state* and opaque references; raw PII columns
	// (full_name_enc, dob_enc, ...) are written by the eKYC ingestion path, not
	// here. Retention (retain_until) follows Decree 147 (>= 24 months).
	// Establishes the vault row in its default unverified, non-adult state.
	// Idempotent so bootstrap/relink paths can call it unconditionally.
	CreateIdentityRecord(ctx context.Context, userID string) error
	CreateLoginChallenge(ctx context.Context, arg CreateLoginChallengeParams) error
	CreatePhoneChallenge(ctx context.Context, arg CreatePhoneChallengeParams) error
	// Sessions and their participants. The kind/class_id coherence CHECK and the
	// direct-session participant cap are enforced DB-side; these queries surface
	// those guarantees rather than re-implementing them.
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Users: opaque-id accounts, no PII (PII lives in identity_vault). Activation
	// is gated DB-side by the verified-adult trigger; these queries never bypass it.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CurrentTokenVersion(ctx context.Context, id string) (int32, error)
	EndSession(ctx context.Context, id string) error
	// The newest unconsumed, unexpired challenge for an email.
	GetActiveLoginChallenge(ctx context.Context, email string) (LoginChallenge, error)
	GetActivePhoneChallenge(ctx context.Context, phone string) (PhoneChallenge, error)
	GetClass(ctx context.Context, id string) (Class, error)
	// First-party email-OTP login. Login factor only; never adult eKYC.
	GetEmailIdentity(ctx context.Context, email string) (EmailIdentity, error)
	// Resolves the rotation family a presented token belongs to (any state), so a
	// logout can revoke the whole chain.
	GetFamilyByHash(ctx context.Context, tokenHash []byte) (string, error)
	// Federated (OIDC) login identities. Login factor only; never adult eKYC.
	GetFederatedIdentity(ctx context.Context, arg GetFederatedIdentityParams) (FederatedIdentity, error)
	GetIdentity(ctx context.Context, userID string) (IdentityVault, error)
	// Phone one-time-code factor: login + the phone_verified assurance tier.
	GetPhoneIdentity(ctx context.Context, phone string) (PhoneIdentity, error)
	GetPhoneIdentityByUser(ctx context.Context, userID string) (PhoneIdentity, error)
	// Locks the row for the duration of the rotation transaction so a token
	// presented concurrently cannot rotate twice (serialises reuse detection).
	GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash []byte) (RefreshToken, error)
	GetSession(ctx context.Context, id string) (Session, error)
	GetUser(ctx context.Context, id string) (User, error)
	// Login lookup. Case-insensitive (matches the lower(handle) unique index) and
	// excludes soft-deleted accounts.
	GetUserByHandle(ctx context.Context, lower string) (User, error)
	// True if the user has self-attested 18+ under any ToS version.
	HasAdultAttestation(ctx context.Context, userID string) (bool, error)
	HasVerifiedPhone(ctx context.Context, userID string) (bool, error)
	IncrementLoginChallengeAttempts(ctx context.Context, id string) error
	IncrementPhoneChallengeAttempts(ctx context.Context, id string) error
	// Access-token revocation state (A-5): the parts of validation the stateless
	// signature check cannot answer. Backs token.RevocationStore.
	IsAccessTokenRevoked(ctx context.Context, jti string) (bool, error)
	// Refresh-token rotation chain (A-5). Tokens are opaque and stored only as a
	// hash; rotation is single-use with reuse detection at the family level.
	IssueRefreshToken(ctx context.Context, arg IssueRefreshTokenParams) error
	LinkEmailIdentity(ctx context.Context, arg LinkEmailIdentityParams) error
	LinkFederatedIdentity(ctx context.Context, arg LinkFederatedIdentityParams) error
	LinkPhoneIdentity(ctx context.Context, arg LinkPhoneIdentityParams) error
	ListActiveParticipants(ctx context.Context, sessionID string) ([]SessionParticipant, error)
	ListClassesByInstructor(ctx context.Context, instructorID string) ([]Class, error)
	// Public catalog: published classes, newest first (bounded).
	ListPublishedClasses(ctx context.Context) ([]Class, error)
	// A class's sessions for discovery: soonest-scheduled first, then newest.
	ListSessionsByClass(ctx context.Context, classID *string) ([]Session, error)
	MarkRefreshTokenReplaced(ctx context.Context, arg MarkRefreshTokenReplacedParams) error
	// Grants the platform-moderator capability (backs caps:platform_moderator).
	// Operator-only path (adminctl); never reachable from user-facing handlers.
	PromoteToModerator(ctx context.Context, id string) error
	RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error
	// Single-token revocation: denylist a jti until its natural expiry. Idempotent.
	RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) error
	// Reverses verification (e.g. eKYC reversal, fraud finding). Defence in depth:
	// a trigger demotes any active user whose identity is revoked this way.
	RevokeIdentityVerification(ctx context.Context, userID string) error
	// Theft response: revoke every live token in the rotation chain at once.
	RevokeRefreshFamily(ctx context.Context, familyID string) error
	// Marks a verification as in-flight when an eKYC session is started.
	SetIdentityVerificationPending(ctx context.Context, userID string) error
	SoftDeleteUser(ctx context.Context, id string) error
	StartSession(ctx context.Context, id string) error
	SuspendUser(ctx context.Context, id string) error
	TouchEmailLogin(ctx context.Context, email string) error
	TouchFederatedLogin(ctx context.Context, arg TouchFederatedLoginParams) error
	TouchPhoneLogin(ctx context.Context, phone string) error
	UpdateClassStatus(ctx context.Context, arg UpdateClassStatusParams) error
	// Sets the user-editable profile fields. handle uniqueness is enforced by the
	// lower(handle) unique index (a conflict surfaces as a unique violation).
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) error
	UserExists(ctx context.Context, id string) (bool, error)
	// Records a successful eKYC: verified adult. This is the state the activation
	// trigger requires before a user may go active.
	VerifyAdultIdentity(ctx context.Context, arg VerifyAdultIdentityParams) error
}

var _ Querier = (*Queries)(nil)
