// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh.sql

package sqlcdb

import (
	"context"
	"time"
)

const getFamilyByHash = `-- name: GetFamilyByHash :one
SELECT family_id FROM refresh_tokens WHERE token_hash = $1
`

// Resolves the rotation family a presented token belongs to (any state), so a
// logout can revoke the whole chain.
func (q *Queries) GetFamilyByHash(ctx context.Context, tokenHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, getFamilyByHash, tokenHash)
	var family_id string
	err := row.Scan(&family_id)
	return family_id, err
}

const getRefreshTokenByHashForUpdate = `-- name: GetRefreshTokenByHashForUpdate :one
SELECT id, user_id, family_id, token_hash, expires_at, revoked_at, replaced_by_id, created_at
FROM refresh_tokens
WHERE token_hash = $1
FOR UPDATE
`

// Locks the row for the duration of the rotation transaction so a token
// presented concurrently cannot rotate twice (serialises reuse detection).
func (q *Queries) GetRefreshTokenByHashForUpdate(ctx context.Context, tokenHash []byte) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHashForUpdate, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FamilyID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByID,
		&i.CreatedAt,
	)
	return i, err
}

const issueRefreshToken = `-- name: IssueRefreshToken :exec

INSERT INTO refresh_tokens (id, user_id, family_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type IssueRefreshTokenParams struct {
	ID        string
	UserID    string
	FamilyID  string
	TokenHash []byte
	ExpiresAt time.Time
}

// Refresh-token rotation chain (A-5). Tokens are opaque and stored only as a
// hash; rotation is single-use with reuse detection at the family level.
func (q *Queries) IssueRefreshToken(ctx context.Context, arg IssueRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, issueRefreshToken,
		arg.ID,
		arg.UserID,
		arg.FamilyID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const markRefreshTokenReplaced = `-- name: MarkRefreshTokenReplaced :exec
UPDATE refresh_tokens
SET revoked_at = now(), replaced_by_id = $2
WHERE id = $1
`

type MarkRefreshTokenReplacedParams struct {
	ID           string
	ReplacedByID *string
}

func (q *Queries) MarkRefreshTokenReplaced(ctx context.Context, arg MarkRefreshTokenReplacedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenReplaced, arg.ID, arg.ReplacedByID)
	return err
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :exec
UPDATE refresh_tokens
SET revoked_at = now()
WHERE family_id = $1 AND revoked_at IS NULL
`

// Theft response: revoke every live token in the rotation chain at once.
func (q *Queries) RevokeRefreshFamily(ctx context.Context, familyID string) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamily, familyID)
	return err
}
