// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcdb

import (
	"context"
	"time"
)

const addParticipant = `-- name: AddParticipant :exec
INSERT INTO session_participants (session_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddParticipantParams struct {
	SessionID string
	UserID    string
	Role      string
}

// Subject to trg_enforce_direct_session_cap for direct sessions.
func (q *Queries) AddParticipant(ctx context.Context, arg AddParticipantParams) error {
	_, err := q.db.Exec(ctx, addParticipant, arg.SessionID, arg.UserID, arg.Role)
	return err
}

const createSession = `-- name: CreateSession :one

INSERT INTO sessions (id, kind, class_id, livekit_room, scheduled_start)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, kind, class_id, livekit_room, status, scheduled_start, started_at, ended_at, created_at
`

type CreateSessionParams struct {
	ID             string
	Kind           string
	ClassID        *string
	LivekitRoom    string
	ScheduledStart *time.Time
}

// Sessions and their participants. The kind/class_id coherence CHECK and the
// direct-session participant cap are enforced DB-side; these queries surface
// those guarantees rather than re-implementing them.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.Kind,
		arg.ClassID,
		arg.LivekitRoom,
		arg.ScheduledStart,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ClassID,
		&i.LivekitRoom,
		&i.Status,
		&i.ScheduledStart,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const endSession = `-- name: EndSession :exec
UPDATE sessions SET status = 'ended', ended_at = now() WHERE id = $1
`

func (q *Queries) EndSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, endSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, kind, class_id, livekit_room, status, scheduled_start, started_at, ended_at, created_at
FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ClassID,
		&i.LivekitRoom,
		&i.Status,
		&i.ScheduledStart,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveParticipants = `-- name: ListActiveParticipants :many
SELECT session_id, user_id, role, joined_at, left_at
FROM session_participants
WHERE session_id = $1 AND left_at IS NULL
ORDER BY joined_at
`

func (q *Queries) ListActiveParticipants(ctx context.Context, sessionID string) ([]SessionParticipant, error) {
	rows, err := q.db.Query(ctx, listActiveParticipants, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionParticipant{}
	for rows.Next() {
		var i SessionParticipant
		if err := rows.Scan(
			&i.SessionID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.LeftAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByClass = `-- name: ListSessionsByClass :many
SELECT id, kind, class_id, livekit_room, status, scheduled_start, started_at, ended_at, created_at
FROM sessions WHERE class_id = $1
ORDER BY scheduled_start ASC NULLS LAST, created_at DESC
LIMIT 100
`

// A class's sessions for discovery: soonest-scheduled first, then newest.
func (q *Queries) ListSessionsByClass(ctx context.Context, classID *string) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.ClassID,
			&i.LivekitRoom,
			&i.Status,
			&i.ScheduledStart,
			&i.StartedAt,
			&i.EndedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeParticipant = `-- name: RemoveParticipant :exec
UPDATE session_participants SET left_at = now()
WHERE session_id = $1 AND user_id = $2 AND left_at IS NULL
`

type RemoveParticipantParams struct {
	SessionID string
	UserID    string
}

func (q *Queries) RemoveParticipant(ctx context.Context, arg RemoveParticipantParams) error {
	_, err := q.db.Exec(ctx, removeParticipant, arg.SessionID, arg.UserID)
	return err
}

const startSession = `-- name: StartSession :exec
UPDATE sessions SET status = 'live', started_at = now() WHERE id = $1
`

func (q *Queries) StartSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, startSession, id)
	return err
}
