// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package sqlcdb

import (
	"context"
	"time"
)

const bumpTokenVersion = `-- name: BumpTokenVersion :one
UPDATE users SET token_version = token_version + 1
WHERE id = $1
RETURNING token_version
`

// Revoke-all for a user: every outstanding access token (tver < new) is now
// superseded. Returns the new version.
func (q *Queries) BumpTokenVersion(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, bumpTokenVersion, id)
	var token_version int32
	err := row.Scan(&token_version)
	return token_version, err
}

const currentTokenVersion = `-- name: CurrentTokenVersion :one
SELECT token_version FROM users WHERE id = $1
`

func (q *Queries) CurrentTokenVersion(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, currentTokenVersion, id)
	var token_version int32
	err := row.Scan(&token_version)
	return token_version, err
}

const isAccessTokenRevoked = `-- name: IsAccessTokenRevoked :one

SELECT EXISTS (
    SELECT 1 FROM revoked_tokens WHERE jti = $1
)
`

// Access-token revocation state (A-5): the parts of validation the stateless
// signature check cannot answer. Backs token.RevocationStore.
func (q *Queries) IsAccessTokenRevoked(ctx context.Context, jti string) (bool, error) {
	row := q.db.QueryRow(ctx, isAccessTokenRevoked, jti)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const revokeAccessToken = `-- name: RevokeAccessToken :exec
INSERT INTO revoked_tokens (jti, expires_at)
VALUES ($1, $2)
ON CONFLICT (jti) DO NOTHING
`

type RevokeAccessTokenParams struct {
	Jti       string
	ExpiresAt time.Time
}

// Single-token revocation: denylist a jti until its natural expiry. Idempotent.
func (q *Queries) RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) error {
	_, err := q.db.Exec(ctx, revokeAccessToken, arg.Jti, arg.ExpiresAt)
	return err
}

const revokeAllRefreshTokens = `-- name: RevokeAllRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now()
WHERE user_id = $1 AND revoked_at IS NULL
`

// Revoke every live refresh token for a user (used by "log out everywhere").
func (q *Queries) RevokeAllRefreshTokens(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokens, userID)
	return err
}
