// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tos.sql

package sqlcdb

import (
	"context"
)

const acceptToS = `-- name: AcceptToS :exec

INSERT INTO tos_acceptances (user_id, tos_version, adult_attested)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, tos_version)
DO UPDATE SET adult_attested = EXCLUDED.adult_attested, accepted_at = now()
`

type AcceptToSParams struct {
	UserID        string
	TosVersion    string
	AdultAttested bool
}

// Terms-of-Service acceptances, including the explicit 18+ self-attestation that
// backs the 'declared' identity-assurance tier.
// Idempotent per (user, version): re-accepting updates the attestation/time.
func (q *Queries) AcceptToS(ctx context.Context, arg AcceptToSParams) error {
	_, err := q.db.Exec(ctx, acceptToS, arg.UserID, arg.TosVersion, arg.AdultAttested)
	return err
}

const hasAdultAttestation = `-- name: HasAdultAttestation :one
SELECT EXISTS (
    SELECT 1 FROM tos_acceptances
    WHERE user_id = $1 AND adult_attested = true
)
`

// True if the user has self-attested 18+ under any ToS version.
func (q *Queries) HasAdultAttestation(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasAdultAttestation, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
