// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcdb

import (
	"context"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE users SET status = 'active' WHERE id = $1
`

// Subject to trg_enforce_adult_activation: fails unless a verified adult
// identity exists for the user.
func (q *Queries) ActivateUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, activateUser, id)
	return err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (id, handle, display_name, locale, can_instruct)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, handle, display_name, bio, locale, status, can_instruct, is_platform_moderator, token_version, created_at, deleted_at
`

type CreateUserParams struct {
	ID          string
	Handle      string
	DisplayName string
	Locale      string
	CanInstruct bool
}

// Users: opaque-id accounts, no PII (PII lives in identity_vault). Activation
// is gated DB-side by the verified-adult trigger; these queries never bypass it.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Handle,
		arg.DisplayName,
		arg.Locale,
		arg.CanInstruct,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Bio,
		&i.Locale,
		&i.Status,
		&i.CanInstruct,
		&i.IsPlatformModerator,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, handle, display_name, bio, locale, status, can_instruct, is_platform_moderator, token_version, created_at, deleted_at
FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Bio,
		&i.Locale,
		&i.Status,
		&i.CanInstruct,
		&i.IsPlatformModerator,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByHandle = `-- name: GetUserByHandle :one
SELECT id, handle, display_name, bio, locale, status, can_instruct, is_platform_moderator, token_version, created_at, deleted_at
FROM users WHERE lower(handle) = lower($1) AND deleted_at IS NULL
`

// Login lookup. Case-insensitive (matches the lower(handle) unique index) and
// excludes soft-deleted accounts.
func (q *Queries) GetUserByHandle(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByHandle, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.DisplayName,
		&i.Bio,
		&i.Locale,
		&i.Status,
		&i.CanInstruct,
		&i.IsPlatformModerator,
		&i.TokenVersion,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users SET status = 'deleted', deleted_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const suspendUser = `-- name: SuspendUser :exec
UPDATE users SET status = 'suspended' WHERE id = $1
`

func (q *Queries) SuspendUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, suspendUser, id)
	return err
}
